from . import meli_category
from . import product_template
from . import meli_instance
from . import meli_item
from . import meli_attribute
from . import meli_payment_method
from . import sale_order
from . import account_move
from . import res_partner
from . import meli_product_image
