from odoo import models, fields, api, _
from odoo.exceptions import UserError
import requests
import datetime
import logging

_logger = logging.getLogger(__name__)

_MELI_SITES = {
    'MLA': {'name': 'Argentina', 'auth_domain': 'auth.mercadolibre.com.ar', 'currency': 'ARS'},
    'MLB': {'name': 'Brasil',    'auth_domain': 'auth.mercadolibre.com.br', 'currency': 'BRL'},
    'MLC': {'name': 'Chile',     'auth_domain': 'auth.mercadolibre.cl',     'currency': 'CLP'},
    'MLM': {'name': 'México',    'auth_domain': 'auth.mercadolibre.com.mx', 'currency': 'MXN'},
    'MLU': {'name': 'Uruguay',   'auth_domain': 'auth.mercadolibre.com.uy', 'currency': 'UYU'},
    'MCO': {'name': 'Colombia',  'auth_domain': 'auth.mercadolibre.com.co', 'currency': 'COP'},
    'MPE': {'name': 'Perú',      'auth_domain': 'auth.mercadolibre.com.pe', 'currency': 'PEN'},
    'MLV': {'name': 'Venezuela', 'auth_domain': 'auth.mercadolibre.com.ve', 'currency': 'VES'},
}


class MeliInstance(models.Model):
    _name = 'meli.instance'
    _description = 'MercadoLibre Instance'

    name = fields.Char('Account Name', required=True)
    site_id = fields.Selection([
        ('MLA', 'Argentina'),
        ('MLB', 'Brasil'),
        ('MLC', 'Chile'),
        ('MLM', 'México'),
        ('MLU', 'Uruguay'),
        ('MCO', 'Colombia'),
        ('MPE', 'Perú'),
        ('MLV', 'Venezuela'),
    ], string='País / Site', default='MLA', required=True)
    currency_ml = fields.Char('Moneda ML', compute='_compute_currency_ml', store=False)

    app_id = fields.Char('App ID', required=True)
    secret_key = fields.Char('Secret Key', required=True)
    redirect_uri = fields.Char(
        'Redirect URI', required=True,
        help='The exact redirect URI configured in MercadoLibre App',
        default=lambda self: self.env['ir.config_parameter'].sudo().get_param('web.base.url') + '/meli/auth'
    )

    authorization_code = fields.Char(
        'Authorization Code',
        help='Code returned by MercadoLibre after user authorizes the app'
    )
    access_token = fields.Char('Access Token', readonly=True)
    refresh_token = fields.Char('Refresh Token', readonly=True)
    token_expiration = fields.Datetime('Token Expiration', readonly=True)

    pricelist_id = fields.Many2one('product.pricelist', string='Pricelist (ML Prices)')
    stock_location_ids = fields.Many2many('stock.location', string='Stock Locations')
    seller_id = fields.Char('Seller ID', readonly=True)

    state = fields.Selection([
        ('draft', 'Draft'),
        ('authenticated', 'Authenticated'),
        ('error', 'Error')
    ], string='Status', default='draft', readonly=True)

    @api.depends('site_id')
    def _compute_currency_ml(self):
        for rec in self:
            rec.currency_ml = _MELI_SITES.get(rec.site_id or 'MLA', {}).get('currency', 'ARS')

    def action_get_authorization_url(self):
        self.ensure_one()
        if not self.app_id or not self.redirect_uri:
            raise UserError(_("Please configure App ID and Redirect URI first."))

        auth_domain = _MELI_SITES.get(self.site_id, {}).get('auth_domain', 'auth.mercadolibre.com.ar')
        url = (
            f"https://{auth_domain}/authorization"
            f"?response_type=code&client_id={self.app_id}&redirect_uri={self.redirect_uri}"
            f"&access_type=offline"
        )
        return {
            'type': 'ir.actions.act_url',
            'url': url,
            'target': 'new',
        }

    def action_get_token(self):
        self.ensure_one()
        if not self.authorization_code:
            raise UserError(_("Please provide the Authorization Code generated by MercadoLibre."))

        url = "https://api.mercadolibre.com/oauth/token"
        headers = {
            'accept': 'application/json',
            'content-type': 'application/x-www-form-urlencoded'
        }
        data = {
            'grant_type': 'authorization_code',
            'client_id': self.app_id.strip(),
            'client_secret': self.secret_key.strip(),
            'code': self.authorization_code.strip(),
            'redirect_uri': self.redirect_uri.strip(),
        }

        try:
            _logger.info("Requesting ML token for %s with App ID %s...", self.name, self.app_id.strip()[:5])
            response = requests.post(url, headers=headers, data=data)
            _logger.info("ML OAuth Response (%s): %s", response.status_code, response.text)
            self._process_token_response(response)
        except Exception as e:
            self.write({'state': 'error'})
            _logger.error("Error requesting ML token: %s", str(e))
            raise UserError(_("Error requesting token: %s") % str(e))

    def action_refresh_token(self):
        for rec in self:
            if not rec.refresh_token:
                msg = "Cannot refresh token for %s: No refresh_token found!" % rec.name
                _logger.error(msg)
                if not self.env.context.get('cron_mode'):
                    raise UserError(_(msg))
                continue

            url = "https://api.mercadolibre.com/oauth/token"
            headers = {
                'accept': 'application/json',
                'content-type': 'application/x-www-form-urlencoded'
            }
            data = {
                'grant_type': 'refresh_token',
                'client_id': rec.app_id.strip(),
                'client_secret': rec.secret_key.strip(),
                'refresh_token': rec.refresh_token.strip(),
            }

            try:
                _logger.info("Refreshing ML token for %s...", rec.name)
                response = requests.post(url, headers=headers, data=data)
                _logger.info("ML Refresh Response (%s): %s", response.status_code, response.text)
                rec._process_token_response(response)
            except Exception as e:
                rec.write({'state': 'error'})
                _logger.error("Error refreshing ML token for %s: %s", rec.name, str(e))
                if not self.env.context.get('cron_mode'):
                    raise UserError(_("Error refreshing token: %s") % str(e))

    def _process_token_response(self, response):
        if response.status_code == 200:
            res_data = response.json()
            expires_in = res_data.get('expires_in', 21600)
            user_id = str(res_data.get('user_id', ''))
            access_token = res_data.get('access_token', '').strip()
            new_refresh_token = res_data.get('refresh_token', '').strip()

            # Preserve existing refresh_token if ML doesn't return a new one
            # (ML only returns refresh_token on initial auth with access_type=offline)
            vals = {
                'access_token': access_token,
                'token_expiration': fields.Datetime.now() + datetime.timedelta(seconds=expires_in),
                'state': 'authenticated',
                'authorization_code': False,
            }
            if new_refresh_token:
                vals['refresh_token'] = new_refresh_token
                _logger.info("ML OAuth: refresh_token received and saved for %s", self.name)
            else:
                _logger.warning(
                    "ML OAuth: no refresh_token in response for %s. "
                    "Ensure the ML app has 'offline_access' enabled and re-authorize with access_type=offline.",
                    self.name
                )
            if user_id:
                vals['seller_id'] = user_id

            self.sudo().write(vals)
        else:
            error_msg = response.text
            self.write({'state': 'error'})
            _logger.error("ML OAuth Error: %s", error_msg)
            raise UserError(_("MercadoLibre rejected the request: %s") % error_msg)

    def action_reset_connection(self):
        self.ensure_one()
        self.write({
            'state': 'draft',
            'authorization_code': False,
            'access_token': False,
            'refresh_token': False,
            'token_expiration': False,
            'seller_id': False,
        })

    def _call_api(self, method, url, **kwargs):
        """
        Generic API wrapper with automatic token validation and retry on 401.
        """
        self.ensure_one()
        self.check_token_validity()

        headers = kwargs.get('headers') or {}
        headers['Authorization'] = f'Bearer {self.access_token}'
        kwargs['headers'] = headers

        _logger.info("ML API Call: %s %s", method, url)
        response = requests.request(method, url, **kwargs)

        if response.status_code == 401:
            _logger.warning("401 Unauthorized for %s — refreshing token for %s...", url, self.name)

            try:
                self.sudo().action_refresh_token()
            except Exception as e:
                _logger.error("Token refresh exception for %s: %s", self.name, str(e))
                return response

            # Force re-read from DB after refresh
            self.invalidate_recordset(['access_token', 'refresh_token'])
            new_token = self.sudo().access_token

            if not new_token:
                _logger.error("Token refresh FAILED for %s: no token after refresh.", self.name)
                return response

            _logger.info("Retrying ML API Call with refreshed token for %s...", self.name)
            headers['Authorization'] = f'Bearer {new_token}'
            kwargs['headers'] = headers
            response = requests.request(method, url, **kwargs)

            if response.status_code == 401:
                _logger.error("STILL 401 after token refresh for %s: %s", self.name, response.text)

        return response

    def check_token_validity(self):
        """Validate token before API requests, refreshing if expiring within 5 minutes."""
        self.ensure_one()
        if not self.access_token:
            raise UserError(_("Not authenticated with MercadoLibre Account '%s'.") % self.name)

        limit_time = fields.Datetime.now() + datetime.timedelta(minutes=5)
        if self.token_expiration and self.token_expiration <= limit_time:
            self.action_refresh_token()

    def cron_refresh_tokens(self):
        """Proactively refresh tokens expiring in the next 30 minutes."""
        limit_time = fields.Datetime.now() + datetime.timedelta(minutes=30)
        instances = self.search([
            ('state', '=', 'authenticated'),
            ('token_expiration', '<=', limit_time),
        ])
        instances.with_context(cron_mode=True).action_refresh_token()

    def action_sync_root_categories(self):
        self.ensure_one()
        url = f"https://api.mercadolibre.com/sites/{self.site_id}/categories"
        response = self._call_api('GET', url)
        if response.status_code == 200:
            for cat in response.json():
                if not self.env['meli.category'].search([('meli_id', '=', cat['id'])]):
                    self.env['meli.category'].create({
                        'name': cat['name'],
                        'meli_id': cat['id'],
                    })
        else:
            raise UserError(_("Error syncing categories: %s") % response.text)

    def _ensure_seller_id(self):
        """Fetch and cache seller_id if not already set. Returns seller_id or None."""
        self.ensure_one()
        if self.seller_id:
            return self.seller_id
        try:
            resp = self._call_api('GET', "https://api.mercadolibre.com/users/me")
            if resp.status_code == 200:
                seller_id = str(resp.json().get('id'))
                self.sudo().write({'seller_id': seller_id})
                return seller_id
            _logger.error("Failed to fetch ML seller info for %s: %s", self.name, resp.text)
        except Exception as e:
            _logger.error("Exception fetching seller info for %s: %s", self.name, str(e))
        return None

    def _process_single_order(self, order):
        """Create a sale.order from an ML order dict if it doesn't already exist."""
        order_id = str(order.get('id'))
        if self.env['sale.order'].search([('meli_order_id', '=', order_id)], limit=1):
            return

        buyer = order.get('buyer') or {}
        nickname = buyer.get('nickname') or 'MercadoLibre Guest'
        meli_user_id = str(buyer.get('id', ''))

        partner = self.env['res.partner'].search([('meli_user_id', '=', meli_user_id)], limit=1)
        if not partner:
            partner = self.env['res.partner'].search([('name', '=', nickname)], limit=1)
        if not partner:
            partner = self.env['res.partner'].create({
                'name': nickname,
                'meli_user_id': meli_user_id,
                'meli_nickname': nickname,
            })
        elif not partner.meli_user_id:
            partner.write({'meli_user_id': meli_user_id, 'meli_nickname': nickname})

        order_lines = []
        for item in order.get('order_items', []):
            meli_item_id = item.get('item', {}).get('id')
            qty = item.get('quantity', 1)
            price = item.get('unit_price', 0)
            m_item = self.env['meli.item'].search([('meli_id', '=', meli_item_id)], limit=1)
            if m_item and m_item.product_id:
                order_lines.append((0, 0, {
                    'product_id': m_item.product_id.product_variant_id.id,
                    'product_uom_qty': qty,
                    'price_unit': price,
                }))

        if order_lines:
            so = self.env['sale.order'].create({
                'partner_id': partner.id,
                'meli_order_id': order_id,
                'meli_instance_id': self.id,
                'state': 'draft',
                'order_line': order_lines,
            })
            so.action_confirm()
            _logger.info("Created sale order %s for ML order %s", so.name, order_id)

    def action_sync_orders(self):
        for rec in self:
            if rec.state != 'authenticated':
                continue

            seller_id = rec._ensure_seller_id()
            if not seller_id:
                continue

            try:
                orders_url = "https://api.mercadolibre.com/orders/search"
                offset = 0
                limit = 50

                while True:
                    params = {
                        'seller': seller_id,
                        'order.status': 'paid',
                        'offset': offset,
                        'limit': limit,
                    }
                    response = rec._call_api('GET', orders_url, params=params)

                    if response.status_code != 200:
                        _logger.error("Error searching orders for %s: %s", rec.name, response.text)
                        break

                    data = response.json()
                    orders = data.get('results', [])
                    if not orders:
                        break

                    for order in orders:
                        rec._process_single_order(order)

                    offset += limit
                    total = data.get('paging', {}).get('total', 0)
                    if offset >= total:
                        break

            except Exception as e:
                _logger.error("Exception while syncing orders for %s: %s", rec.name, str(e))
                if not self.env.context.get('cron_mode'):
                    raise

    @api.model
    def cron_sync_orders(self):
        instances = self.search([('state', '=', 'authenticated')])
        instances.with_context(cron_mode=True).action_sync_orders()

    def action_sync_items(self):
        self.ensure_one()
        self.env['meli.item'].with_context(
            cron_mode=self.env.context.get('cron_mode')
        ).action_import_items(self)
