from odoo import models, fields, api, _
from odoo.exceptions import UserError
import requests
import datetime
import logging

_logger = logging.getLogger(__name__)

class MeliInstance(models.Model):
    _name = 'meli.instance'
    _description = 'MercadoLibre Instance'

    name = fields.Char('Account Name', required=True)
    app_id = fields.Char('App ID', required=True)
    secret_key = fields.Char('Secret Key', required=True)
    redirect_uri = fields.Char('Redirect URI', required=True, 
                              help='The exact redirect URI configured in MercadoLibre App',
                              default=lambda self: self.env['ir.config_parameter'].sudo().get_param('web.base.url') + '/meli/auth')
    
    authorization_code = fields.Char('Authorization Code', help='Code returned by MercadoLibre after user authorizes the app')
    access_token = fields.Char('Access Token', readonly=True)
    refresh_token = fields.Char('Refresh Token', readonly=True)
    token_expiration = fields.Datetime('Token Expiration', readonly=True)
    
    pricelist_id = fields.Many2one('product.pricelist', string='Pricelist (ML Prices)')
    stock_location_ids = fields.Many2many('stock.location', string='Stock Locations')
    seller_id = fields.Char('Seller ID', readonly=True)
    
    state = fields.Selection([
        ('draft', 'Draft'),
        ('authenticated', 'Authenticated'),
        ('error', 'Error')
    ], string='Status', default='draft', readonly=True)

    def action_get_authorization_url(self):
        self.ensure_one()
        if not self.app_id or not self.redirect_uri:
            raise UserError(_("Please configure App ID and Redirect URI first."))
        
        # Argentina URL by default, could be dynamic depending on country
        url = f"https://auth.mercadolibre.com.ar/authorization?response_type=code&client_id={self.app_id}&redirect_uri={self.redirect_uri}"
        
        return {
            'type': 'ir.actions.act_url',
            'url': url,
            'target': 'new',
        }

    def action_get_token(self):
        self.ensure_one()
        if not self.authorization_code:
            raise UserError(_("Please provide the Authorization Code generated by MercadoLibre."))
            
        url = "https://api.mercadolibre.com/oauth/token"
        headers = {
            'accept': 'application/json',
            'content-type': 'application/x-www-form-urlencoded'
        }
        data = {
            'grant_type': 'authorization_code',
            'client_id': self.app_id,
            'client_secret': self.secret_key,
            'code': self.authorization_code,
            'redirect_uri': self.redirect_uri
        }
        
        try:
            _logger.info(f"Requesting ML token for {self.name} with App ID {self.app_id[:5]}...")
            response = requests.post(url, headers=headers, data=data)
            _logger.info(f"ML OAuth Response ({response.status_code}): {response.text}")
            self._process_token_response(response)
        except Exception as e:
            self.write({'state': 'error'})
            _logger.error(f"Error requesting ML token: {str(e)}")
            raise UserError(_("Error requesting token: %s") % str(e))

    def action_refresh_token(self):
        for rec in self:
            if not rec.refresh_token:
                continue
            
            url = "https://api.mercadolibre.com/oauth/token"
            headers = {
                'accept': 'application/json',
                'content-type': 'application/x-www-form-urlencoded'
            }
            data = {
                'grant_type': 'refresh_token',
                'client_id': rec.app_id.strip(),
                'client_secret': rec.secret_key.strip(),
                'refresh_token': rec.refresh_token.strip()
            }
            
            try:
                _logger.info(f"Refreshing ML token for {rec.name}...")
                response = requests.post(url, headers=headers, data=data)
                _logger.info(f"ML Refresh Response ({response.status_code}): {response.text}")
                rec._process_token_response(response)
            except Exception as e:
                rec.write({'state': 'error'})
                _logger.error(f"Error refreshing ML token for instance {rec.name}: {str(e)}")

    def _process_token_response(self, response):
        if response.status_code == 200:
            res_data = response.json()
            expires_in = res_data.get('expires_in', 21600)  # usually 6 hours
            user_id = str(res_data.get('user_id', ''))
            access_token = res_data.get('access_token', '').strip()
            refresh_token = res_data.get('refresh_token', '').strip()
            
            self.sudo().write({
                'access_token': access_token,
                'refresh_token': refresh_token,
                'token_expiration': fields.Datetime.now() + datetime.timedelta(seconds=expires_in),
                'state': 'authenticated',
                'seller_id': user_id,
            })
        else:
            self.write({'state': 'error'})
            raise UserError(_("Error getting token: %s") % response.text)

    def action_reset_connection(self):
        self.ensure_one()
        self.write({
            'state': 'draft',
            'authorization_code': False,
            'access_token': False,
            'refresh_token': False,
            'token_expiration': False,
            'seller_id': False,
        })

    def _call_api(self, method, url, **kwargs):
        """
        Generic method to call ML API with token management and auto-retry on 401.
        """
        self.ensure_one()
        self.check_token_validity()
        
        headers = kwargs.get('headers', {}) or {}
        # Ensure latest access token is used
        headers['Authorization'] = f'Bearer {self.access_token}'
        kwargs['headers'] = headers
        
        _logger.info(f"ML API Call: {method} {url} with token ending in ...{self.access_token[-10:] if self.access_token else 'None'}")
        response = requests.request(method, url, **kwargs)
        
        if response.status_code == 401:
            _logger.warning(f"401 Unauthorized for {url}, attempting token refresh for {self.name}...")
            # Use sudo to avoid any permission issue during write
            self.sudo().action_refresh_token()
            
            # Explicitly force-refresh cache from DB
            self.invalidate_recordset(['access_token', 'refresh_token'])
            new_token = self.sudo().access_token
            
            _logger.info(f"Retrying ML API Call with new token ending in ...{new_token[-10:] if new_token else 'None'}")
            headers['Authorization'] = f'Bearer {new_token}'
            kwargs['headers'] = headers
            response = requests.request(method, url, **kwargs)
            
            if response.status_code == 401:
                _logger.error(f"STILL 401 after retry! New token also rejected: {response.text}")
            
        return response

    def check_token_validity(self):
        """Called before API requests to ensure token is valid"""
        self.ensure_one()
        if not self.access_token:
            raise UserError(_("Not authenticated with MercadoLibre Account '%s'.") % self.name)
        
        # Buffer of 5 minutes before actual expiration
        limit_time = fields.Datetime.now() + datetime.timedelta(minutes=5)
        if self.token_expiration and self.token_expiration <= limit_time:
            self.action_refresh_token()
            
    def cron_refresh_tokens(self):
        """Cron method to proactively refresh tokens"""
        # Refresh tokens that expire in the next 30 minutes
        limit_time = fields.Datetime.now() + datetime.timedelta(minutes=30)
        instances = self.search([
            ('state', '=', 'authenticated'),
            ('token_expiration', '<=', limit_time)
        ])
        for instance in instances:
            instance.action_refresh_token()

    def action_sync_root_categories(self):
        self.ensure_one()
        url = "https://api.mercadolibre.com/sites/MLA/categories"
        response = self._call_api('GET', url)
        if response.status_code == 200:
            for cat in response.json():
                existing = self.env['meli.category'].search([('meli_id', '=', cat['id'])])
                if not existing:
                    self.env['meli.category'].create({
                        'name': cat['name'],
                        'meli_id': cat['id'],
                    })

    def action_sync_orders(self):
        for rec in self:
            rec.check_token_validity()
            if rec.state != 'authenticated':
                continue
            
            headers = {'Authorization': f'Bearer {rec.access_token}'}
            seller_id = rec.seller_id
            
            if not seller_id:
                # Fallback to fetch seller info if missing
                users_url = "https://api.mercadolibre.com/users/me"
                try:
                    user_response = rec._call_api('GET', users_url)
                    if user_response.status_code == 200:
                        seller_id = str(user_response.json().get('id'))
                        rec.seller_id = seller_id
                    else:
                        _logger.error(f"Failed to fetch ML seller info: {user_response.text}")
                        continue
                except Exception as e:
                    _logger.error(f"Exception fetching seller info for {rec.name}: {str(e)}")
                    continue
            
            try:
                orders_url = f"https://api.mercadolibre.com/orders/search?seller={seller_id}&order.status=paid"
                response = rec._call_api('GET', orders_url)
                
                if response.status_code == 200:
                    orders = response.json().get('results', [])
                    for order in orders:
                        order_id = str(order.get('id'))
                        existing = self.env['sale.order'].search([('meli_order_id', '=', order_id)])
                        if existing:
                            continue
                            
                        buyer = order.get('buyer', {})
                        nickname = buyer.get('nickname', 'MercadoLibre Guest')
                        meli_user_id = str(buyer.get('id', ''))
                        
                        # Search by Meli User ID (requires inheritance of res.partner)
                        partner = self.env['res.partner'].search([('meli_user_id', '=', meli_user_id)], limit=1)
                        if not partner:
                            partner = self.env['res.partner'].search([('name', '=', nickname)], limit=1)
                            
                        if not partner:
                            partner = self.env['res.partner'].create({
                                'name': nickname,
                                'meli_user_id': meli_user_id,
                                'meli_nickname': nickname,
                            })
                        elif not partner.meli_user_id:
                            partner.write({
                                'meli_user_id': meli_user_id,
                                'meli_nickname': nickname,
                            })
                            
                        # Create Sale Order
                        order_vals = {
                            'partner_id': partner.id,
                            'meli_order_id': order_id,
                            'meli_instance_id': rec.id,
                            'state': 'draft',
                            'order_line': [],
                        }
                        
                        for item in order.get('order_items', []):
                            meli_item_id = item.get('item', {}).get('id')
                            qty = item.get('quantity', 1)
                            price = item.get('unit_price', 0)
                            
                            m_item = self.env['meli.item'].search([('meli_id', '=', meli_item_id)], limit=1)
                            product_id = m_item.product_id.id if m_item else False
                            
                            if product_id:
                                order_vals['order_line'].append((0, 0, {
                                    'product_id': product_id,
                                    'product_uom_qty': qty,
                                    'price_unit': price,
                                }))
                                
                        if order_vals['order_line']:
                            so = self.env['sale.order'].create(order_vals)
                            so.action_confirm()
                else:
                    _logger.error(f"Error searching orders for {rec.name}: {response.text}")
            except Exception as e:
                _logger.error(f"Exception while syncing orders for {rec.name}: {str(e)}")
                continue

    @api.model
    def cron_sync_orders(self):
        instances = self.search([('state', '=', 'authenticated')])
        instances.action_sync_orders()

    def action_sync_items(self):
        self.ensure_one()
        self.env['meli.item'].action_import_items(self)


